
# {{{ Nix
["Nixpkgs packages"]
aliases = ["@np", "@nixpkgs-packages"]
url = "https://search.nixos.org/packages"
param = "query"
icon = "https://raw.githubusercontent.com/NixOS/nixos-artwork/refs/heads/master/logo/nix-snowflake-rainbow.svg"

["Nixos options"]
aliases = ["@no", "@nixos-options"]
url = "https://search.nixos.org/options"
param = "query"
icon = "https://raw.githubusercontent.com/NixOS/nixos-artwork/refs/heads/master/logo/nix-snowflake-rainbow.svg"

["Home-manager options"]
aliases = ["@hm", "@home-manager"]
url = "https://home-manager-options.extranix.com"
param = "query"
icon = "https://raw.githubusercontent.com/NixOS/nixos-artwork/refs/heads/master/logo/nix-snowflake-colours.svg"
# }}}
# {{{ Programming
["Pursuit"]
aliases = ["@ps", "@pursuit"]
url = "https://pursuit.purescript.org/search"
param = "q"
icon = "https://pursuit.purescript.org/static/res/favicon/favicon.ico"

["Hoogle"]
aliases = ["@hg", "@hoogle"]
url = "https://hoogle.haskell.org"
param = "hoogle"
icon = "https://hoogle.haskell.org/favicon.png"

["NPM"]
aliases = ["@npm"]
url = "https://www.npmjs.com/search"
param = "q"
icon = "https://static-00.iconduck.com/assets.00/npm-icon-2048x2048-wm0mnkz6.png"

["Python documentation"]
aliases = ["@py", "@python"]
url = "https://docs.python.org/3/search.html"
param = "q"
icon = "https://docs.python.org/favicon.ico"

["Just documentation"]
aliases = ["@just"]
url = "https://just.systems/man/en/"
param = "search"
icon = "https://just.systems/favicon.ico"

["OpenGL documentation"]
aliases = ["@gl"]
url = "https://docs.gl/"
param = "search"
icon = "https://www.opengl.org/favicon.ico"

["Arch wiki"]
aliases = ["@aw", "@arch-wiki"]
url = "https://wiki.archlinux.org/index.php"
param = "search"
icon = "https://archlinux.org/favicon.ico"

["Github"]
aliases = ["@gh", "@github"]
url = "https://github.com/search"
param = "q"
icon = "https://github.com/favicon.ico"
# }}}
# {{{ Gaming
["Noita wiki"]
aliases = ["@noita"]
url = "https://noita.wiki.gg/index.php"
param = "search"
icon = "https://noita.wiki.gg/favicon.ico"

["Factorio wiki"]
aliases = ["@fw", "@factorio-wiki"]
url = "https://wiki.factorio.com/index.php"
param = "search"
icon = "https://factorio.com/static/img/factorio-wheel.png"

["Factorio mod portal"]
aliases = ["@fm", "@factorio-mods"]
url = "https://mods.factorio.com/"
param = "query"
icon = "https://factorio.com/static/img/factorio-wheel.png"

["Warframe Wiki"]
aliases = ["@wf", "@warframe-wiki"]
url = "https://warframe.fandom.com/wiki/Special:Search"
param = "query"
icon = "https://static.wikia.nocookie.net/warframe/images/e/e6/Site-logo.png"

["Hollow Knight wiki"]
aliases = ["@hk", "@hollow-knight"]
url = "https://hollowknight.wiki/w/index.php"
param = "search"
icon = "https://hollowknight.wiki/favicon.ico"

["Silksong wiki"]
aliases = ["@ss", "@silksong"]
url = "https://hollowknight.wiki/w/index.php"
param = "search"
icon = "https://hollowknight.wiki/favicon.ico"

["Celeste wiki"]
aliases = ["@cel", "@celeste"]
url = "https://celeste.ink/w/index.php"
param = "search"
icon = "https://celeste.ink/favicon.ico"

["Terraria wiki"]
aliases = ["@tr", "@terraria"]
url = "https://terraria.wiki.gg/index.php"
param = "search"
icon = "https://terraria.wiki.gg/favicon.ico"

["Terraria Calamity wiki"]
aliases = ["@cal", "@calamity"]
url = "https://calamitymod.wiki.gg/index.php"
param = "search"
icon = "https://calamitymod.wiki.gg/favicon.ico"

["V Rising wiki"]
aliases = ["@vr", "@vrising"]
url = "https://vrisingwiki.net/index.php"
param = "search"
icon = "https://vrisingwiki.net/favicon.ico"

["Valheim wiki"]
aliases = ["@vh", "@valheim"]
url = "https://valheim.miraheze.org/w/index.php"
param = "search"
icon = "https://valheim.miraheze.org/favicon.ico"

["Expedition 33 wiki"]
aliases = ["@e33", "@expedition33"]
url = "https://expedition33.wiki.fextralife.com/search"
param = "q"
icon = "https://expedition33.wiki.fextralife.com/favicon.ico"
# }}}
# {{{ Misc
["Invidious"]
aliases = ["@yt", "@invidious"]
url = "https://yt.hugo-berendi.de/results"
param = "search_query"
icon = "http://yt.hugo-berendi.de/favicon.ico"

["Youtube"]
aliases = ["@gyt", "@youtube"]
url = "https://www.youtube.com/results"
param = "search_query"
icon = "https://www.youtube.com/favicon.ico"

["searxng"]
aliases = ["@s", "@searxng"]
url = "https://search.hugo-berendi.de/search"
param = "q"
icon = "https://static-00.iconduck.com/assets.00/searxng-icon-1024x1011-xv2s4hfw.png"

["Wikipedia"]
aliases = ["@wk", "@wikipedia"]
url = "https://en.wikipedia.org/wiki/Special:Search"
param = "search"
icon = "https://en.wikipedia.org/favicon.ico"
# }}}
# {{{ AI
["ChatGPT"]
aliases = ["@gpt", "@chatgpt"]
url = "https://chatgpt.com/"
param = "q"
icon = "https://chatgpt.com/favicon.ico"

["Gemini"]
aliases = ["@gem", "@gemini"]
url = "https://gemini.google.com/app"
param = "q"
icon = "https://www.gstatic.com/lamda/images/gemini_favicon_f069958c85030f21b8795710a56a84e56926f4d6.png"

["Claude"]
aliases = ["@cl", "@claude"]
url = "https://claude.ai/new"
param = "q"
icon = "https://claude.ai/favicon.ico"
# }}}
